"""Добавлено отношение между User и Task

Revision ID: 64d17099f62c
Revises: 37c73dbf9a12
Create Date: 2025-01-02 17:09:53.634364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d17099f62c'
down_revision: Union[str, None] = '37c73dbf9a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
